version: "3"
services:
  app:
    build:
      context: ./php
      args:
        - TZ=${TZ}
    volumes:
      - ../myapp:/myapp
      - ./logs:/var/log/php
      - ./php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /myapp
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}